trigger:
  - master

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:.r)

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install NuGet packages and do a nuget restore.
- task: NuGetToolInstaller@0
  displayName: 'Use latest NuGet version'

- task: NuGetCommand@2
  displayName: 'nuget restore'
  inputs:
    restoreSolution: '$(solution)'
    noCache: true

- task: MSBuild@1
  displayName: 'Build $(solution)'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Assemblies'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    artifactName: 'Release'
  condition:
    and(succeeded(), eq(variables['system.pullrequest.isfork'], false))